mapping={
    "serum creatinine":{
		"codes":[
			{
				"system":"http://loinc.org",
				"code":"2160-0",
				"is_regex":False,
				"certitude":2
			}
		],
		"unavailable":{
			"certitude":0
		}
	},
    "pregnancy":{
        "codes":[
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"^Z34\\.",
                "is_regex":True,
				"certitude":2 	
            }
        ],
        "unavailable":{
			"certitude":0
        }
    },
    "bleeding":{
		"codes":[
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"^I60\\.",
                "is_regex":True,
				"certitude":2 
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"^I61\\.",
                "is_regex":True,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"^I62\\.",
                "is_regex":True,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"G95.19",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"T85.830",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H11.3",
                "is_regex":False ,
				"certitude":2            
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H31.3",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H43.1",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H59.1",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H59.3",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"I85.01",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K22.11",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H22.6",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H25.0",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H25.2",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H25.4",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H25.6",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H26.0",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H26.2",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H26.4",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H26.6",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H27.0",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H27.2",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H27.4",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H27.6",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H28.0",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H28.2",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H28.4",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"H28.6",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K29.01",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K31.811",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K92.0",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K55.21",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K57.01",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K57.21",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K57.31",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K57.33",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K57.41",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K57.51",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K57.53",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K57.81",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K57.91",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K57.93",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K62.5",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K92.1",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K92.2",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"K66.1",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"M25.0",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"I31.2",
                "is_regex":False,
				"certitude":2             
            },
            {
                "system":"http://hl7.org/fhir/sid/icd-10-cm",
                "code":"^R58\\.",
                "is_regex":True,
				"certitude":2             
            }
        ],
	"unavailable":{
	    "certitude":0
        }
    },
    "kidney dysfunction":{
		"codes":[
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N00\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N10\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N17\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N14\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"N14.1",
            "is_regex":False,
			"certitude":2            
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"N14.2",
            "is_regex":False,
			"certitude":2            
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"T36.5X5",
            "is_regex":False,
			"certitude":2            
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"B52.0",
            "is_regex":False,
			"certitude":2            
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"D59.3",
            "is_regex":False,
			"certitude":2            
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"E10.2",
            "is_regex":False,
			"certitude":2            
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"E11.2",
            "is_regex":False,
			"certitude":2            
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"E13.2",
            "is_regex":False,
			"certitude":2            
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^I12\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^I13\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"I15.1",
            "is_regex":False,
			"certitude":2            
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"I15.2",
            "is_regex":False,
			"certitude":2            
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N01\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N02\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N03\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N04\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N05\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N06\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N07\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N08\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N11\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N13\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N15\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N16\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N18\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N19\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N25\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N26\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N27\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N28\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N29\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^Q60\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^Q61\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^Q62\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^Q63\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^Z49\\.",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"Z99.2",
            "is_regex":True,
			"certitude":2 
        },
        {
            "system":"http://hl7.org/fhir/sid/icd-10-cm",
            "code":"^N12\\.",
            "is_regex":True,
			"certitude":2 
        }
		],
	"unavailable":{
	    "certitude":0
        }
    }
